export let UserData = [
  {
    id: 1,
    profilePicture: "./public/post/image1.avif",
    userName: "Meetdesai_10",
  },
  {
    id: 2,
    profilePicture: "./public/post/image2.avif",
    userName: "arjunbaldha_25",
  },
  {
    id: 3,
    profilePicture: "./public/post/image3.avif",
    userName: "kashyappatel_63",
  },
  {
    id: 4,
    profilePicture: "./public/post/image4.avif",
    userName: "harshpatel_68",
  },
  {
    id: 5,
    profilePicture: "./public/post/image5.avif",
    userName: "darshantejani_07",
  },
  {
    id: 6,
    profilePicture: "./public/post/image6.avif",
    userName: "harishchauhan_79",
  },
  {
    id: 7,
    profilePicture: "./public/post/image7.avif",
    userName: "pathpatel_94",
  },
  {
    id: 8,
    profilePicture: "./public/post/image8.avif",
    userName: "nirmalkachhdiya_13",
  },
  {
    id: 9,
    profilePicture: "./public/post/image9.avif",
    userName: "snehshah_50",
  },
  {
    id: 10,
    profilePicture: "./public/post/image10.avif",
    userName: "dharmikkyada_25",
  },
];

export let userPostData = [
  {
    id: 1,
    photo: "./public/post/image1.avif",
    date: "10 hr ago",
    userId: "1",
    like: 250,
    comment: 98,
  },
  {
    id: 2,
    photo: "./public/post/image2.avif",
    date: "2 hr ago",
    userId: "2",
    like: 63,
    comment: 39,
  },
  {
    id: 3,
    photo: "./public/post/image3.avif",
    date: "2 min ago",
    userId: "3",
    like: 70,
    comment: 11,
  },
  {
    id: 4,
    photo: "./public/post/image4.avif",
    date: "37 min ago",
    userId: "4",
    like: 50,
    comment: 18,
  },
  {
    id: 5,
    photo: "./public/post/image5.avif",
    date: "19 min ago",
    userId: "5",
    like: 198,
    comment: 50,
  },
  {
    id: 6,
    photo: "./public/post/image6.avif",
    date: "55 min ago",
    userId: "6",
    like: 86,
    comment: 29,
  },
  {
    id: 7,
    photo: "./public/post/image7.avif",
    date: "24 min ago",
    userId: "7",
    like: 16,
    comment: 4,
  },
  {
    id: 8,
    photo: "./public/post/image8.avif",
    date: "1 hr ago",
    userId: "8",
    like: 98,
    comment: 20,
  },
  {
    id: 9,
    photo: "./public/post/image9.avif",
    date: "6 min ago",
    userId: "9",
    like: 120,
    comment: 32,
  },
  {
    id: 10,
    photo: "./public/post/image10.avif",
    date: "50 min ago",
    userId: "10",
    like: 49,
    comment: 15,
  },
];
